import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),base=path.join(root,'content/questions');
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):e.name.endsWith('.md')?[path.join(d,e.name)]:[]);
const ids=new Set(),content=new Set(),bank=[];const allowed=['village','easy','medium','hard','boss'];
for(const file of walk(base).sort()){
 try{const raw=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n');const front=raw.match(/^---\n([\s\S]*?)\n---\n/);if(!front)throw Error('缺少 --- 中繼資料區塊');const meta=Object.fromEntries(front[1].split('\n').filter(Boolean).map(l=>{const i=l.indexOf(':');if(i<1)throw Error('中繼資料必須用 key: value');return[l.slice(0,i).trim(),l.slice(i+1).trim()]}));const title=raw.match(/^# (.+)$/m)?.[1];const sections={};for(const m of raw.matchAll(/^## ([^\n]+)\n([\s\S]*?)(?=^## |$(?![\s\S]))/gm)){if(sections[m[1]])throw Error('重複章節 '+m[1]);sections[m[1]]=m[2].trim()}
 for(const f of ['id','audience','difficulty','answer'])if(!meta[f])throw Error('缺少 '+f);if(!/^[a-z0-9-]+$/.test(meta.id))throw Error('ID 只可使用小寫英文數字與連字號');if(ids.has(meta.id))throw Error('重複 ID '+meta.id);ids.add(meta.id);if(!['kids','adults'].includes(meta.audience)||!allowed.includes(meta.difficulty))throw Error('對象或難度無效');if(!title)throw Error('缺少 # 題目標題');for(const k of ['情境','問題','A','B','C','D','解析','提示','解析 A','解析 B','解析 C','解析 D'])if(!sections[k])throw Error('缺少章節 '+k);if(!['a','b','c','d'].includes(meta.answer))throw Error('正解需為 a、b、c、d');if(new Set(['A','B','C','D'].map(k=>sections[k])).size!==4)throw Error('選項重複');const signature=sections['情境']+'\n'+sections['問題'];if(content.has(signature))throw Error('重複題目情境及問題');content.add(signature);
 const q={...meta,title,scenario:sections['情境'],question:sections['問題'],options:['a','b','c','d'].map(id=>({id,text:sections[id.toUpperCase()],feedback:sections['解析 '+id.toUpperCase()]})),explanation:sections['解析'],hint:sections['提示'],lesson:sections['教學']||''};if(q.difficulty==='boss'){q.round=Number(q.round);if(!q.group||![1,2,3].includes(q.round))throw Error('魔王題需 group 及 round 1–3')}bank.push(q);
 }catch(e){console.error(path.relative(root,file)+': '+e.message);process.exitCode=1}
}
for(const group of new Set(bank.filter(q=>q.difficulty==='boss').map(q=>q.group))){const qs=bank.filter(q=>q.group===group);if(qs.length!==3||new Set(qs.map(q=>q.round)).size!==3||new Set(qs.map(q=>q.audience)).size!==1){console.error('魔王組 '+group+' 必須包含同一對象的 1、2、3 回合各一題');process.exitCode=1}}
if(!bank.length){console.error('題庫不可為空');process.exitCode=1}if(process.exitCode)process.exit(process.exitCode);
fs.mkdirSync(path.join(root,'dist'),{recursive:true});fs.writeFileSync(path.join(root,'dist/questions.json'),JSON.stringify(bank));
console.log('題庫檢查成功：'+bank.length+' 題');for(const a of ['kids','adults'])console.log(a+': '+allowed.map(d=>d+' '+bank.filter(q=>q.audience===a&&q.difficulty===d).length).join(' / '));
